### ISSUE TITLE
Error regarding format of the FSEventsfile

### ISSUE THREAD

**Issue by markedphillips** [dlcowen/FSEventsParser#8]
Tried to run this on a vanilla Mac High Sierra System and it just didn't like the format. Thoughts?

```

[STARTED] 02/06/2019 18:37:26 UTC Parsing files.

  File 3 of 3  [=============================================] 100.0%

[FINISHED] 02/06/2019 18:37:29 UTC Parsing files.

[STARTED] 02/06/2019 18:37:29 UTC Sorting fsevents table in Database.

Traceback (most recent call last):
  File "./FSEParser_V3.3.py", line 1305, in <module>
    main()
  File "./FSEParser_V3.3.py", line 165, in main
    FSEventHandler()
  File "./FSEParser_V3.3.py", line 288, in __init__
    row_count = reorder_sqlite_db(self)
  File "./FSEParser_V3.3.py", line 1264, in reorder_sqlite_db
    SQL_TRAN.execute(query)
sqlite3.OperationalError: error in view UserProfileActivity: no such table: main.fsevents
```

**Comment by gc-nibrahim** [comment]
Thank you for the feedback. Can you provide the 3 files you tried to parse so that I may reproduce the issue?

**Comment by gc-nibrahim** [comment]
Also, what was the command that was run?

**Comment by gc-nibrahim** [comment]
New release version 4.0 should correct this issue. Also, try running the compiled version as it appears to fix the error.
